/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penginapan;

/**
 *
 * @author Hp
 */
public class Hoteltujuan extends javax.swing.JFrame {

    /**
     * Creates new form Hoteltujuan
     */
    public Hoteltujuan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButtonbackhome1 = new javax.swing.JButton();
        jLabeljudulhtujuan = new javax.swing.JLabel();
        jLabelkhusus = new javax.swing.JLabel();
        jLabelprov = new javax.swing.JLabel();
        jLabelkota = new javax.swing.JLabel();
        jLabelhotel = new javax.swing.JLabel();
        jLabelcheckin = new javax.swing.JLabel();
        jLabelcheckout = new javax.swing.JLabel();
        jLabelkamar = new javax.swing.JLabel();
        jLabelharga = new javax.swing.JLabel();
        jComboBoxprov = new javax.swing.JComboBox();
        jComboBoxkota = new javax.swing.JComboBox();
        jTextFieldcheckin = new javax.swing.JTextField();
        jTextFieldcheckout = new javax.swing.JTextField();
        jComboBoxhotel = new javax.swing.JComboBox();
        jComboBoxkamar = new javax.swing.JComboBox();
        jComboBoxharga = new javax.swing.JComboBox();
        jButtoncarihoteltujuan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonbackhome1.setText("<--");

        jLabeljudulhtujuan.setText("nama hotel_hotel tujuan");

        jLabelkhusus.setText("* Khusus Indonesia");

        jLabelprov.setText("Nama Provinsi");

        jLabelkota.setText("Nama Kota");

        jLabelhotel.setText("Nama Hotel");

        jLabelcheckin.setText("Check In");

        jLabelcheckout.setText("Check Out");

        jLabelkamar.setText("Kamar");

        jLabelharga.setText("Filter Harga ");

        jComboBoxprov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Kepulawan Riau", "Jambi", "Bengkulu", "Sumatera Selatan", "Kepulauan Bangka Belitung", "Kampung", " " }));
        jComboBoxprov.setToolTipText("");
        jComboBoxprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxprovActionPerformed(evt);
            }
        });

        jComboBoxkota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Pangkal Pinang", "Medan", "Dumai", "Pekan Baru", "Bukit Tinggi", "Padang", "Binjai" }));
        jComboBoxkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxkotaActionPerformed(evt);
            }
        });

        jTextFieldcheckin.setText("Tanggal check in");

        jTextFieldcheckout.setText("Tanggal check out");

        jComboBoxhotel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));

        jComboBoxkamar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxkamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxkamarActionPerformed(evt);
            }
        });

        jComboBoxharga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Opsional", "Rp.0 - Rp.200.000", "Rp.200.000 - Rp.500.000", "Rp.500.000 - Rp.1.000.000", " " }));

        jButtoncarihoteltujuan.setText("CARI HOTEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelhotel))
                    .addComponent(jButtonbackhome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeljudulhtujuan)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelkhusus)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelprov)
                                    .addComponent(jLabelkota)
                                    .addComponent(jLabelcheckin)
                                    .addComponent(jLabelcheckout)
                                    .addComponent(jLabelkamar)
                                    .addComponent(jLabelharga))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxkota, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxprov, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxkamar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButtoncarihoteltujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonbackhome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeljudulhtujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelkhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelprov)
                    .addComponent(jComboBoxprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelkota)
                    .addComponent(jComboBoxkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelhotel)
                    .addComponent(jComboBoxhotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcheckin)
                    .addComponent(jTextFieldcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcheckout)
                    .addComponent(jTextFieldcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelkamar)
                    .addComponent(jComboBoxkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelharga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addComponent(jButtoncarihoteltujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxprovActionPerformed

    private void jComboBoxkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxkotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxkotaActionPerformed

    private void jComboBoxkamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxkamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxkamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoteltujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoteltujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoteltujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoteltujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoteltujuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbackhome1;
    private javax.swing.JButton jButtoncarihoteltujuan;
    private javax.swing.JComboBox jComboBoxharga;
    private javax.swing.JComboBox jComboBoxhotel;
    private javax.swing.JComboBox jComboBoxkamar;
    private javax.swing.JComboBox jComboBoxkota;
    private javax.swing.JComboBox jComboBoxprov;
    private javax.swing.JLabel jLabelcheckin;
    private javax.swing.JLabel jLabelcheckout;
    private javax.swing.JLabel jLabelharga;
    private javax.swing.JLabel jLabelhotel;
    private javax.swing.JLabel jLabeljudulhtujuan;
    private javax.swing.JLabel jLabelkamar;
    private javax.swing.JLabel jLabelkhusus;
    private javax.swing.JLabel jLabelkota;
    private javax.swing.JLabel jLabelprov;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldcheckin;
    private javax.swing.JTextField jTextFieldcheckout;
    // End of variables declaration//GEN-END:variables
}
