/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penginapan;

/**
 *
 * @author Hp
 */
public class Hotelterdekat extends javax.swing.JFrame {

    /**
     * Creates new form Hotelterdekat
     */
    public Hotelterdekat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonback2 = new javax.swing.JButton();
        jLabeljuduldekat = new javax.swing.JLabel();
        jLabelnginap = new javax.swing.JLabel();
        jLabelCheckin2 = new javax.swing.JLabel();
        jLabelCheckout2 = new javax.swing.JLabel();
        jLabelkamar2 = new javax.swing.JLabel();
        jLabelharga2 = new javax.swing.JLabel();
        jButtonhdekat = new javax.swing.JButton();
        jTextFieldcheckin2 = new javax.swing.JTextField();
        jTextFieldcheckout2 = new javax.swing.JTextField();
        jComboBoxkamar2 = new javax.swing.JComboBox();
        jComboBoxharga2 = new javax.swing.JComboBox();
        jButtoncarihoteldekat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonback2.setText("<-");

        jLabeljuduldekat.setText("nama hotel_hotel terdekat");

        jLabelnginap.setText("nginap ke mana?");

        jLabelCheckin2.setText("Check In");

        jLabelCheckout2.setText("Check Out");

        jLabelkamar2.setText("Kamar");

        jLabelharga2.setText("Filter Harga");

        jButtonhdekat.setText("Hotel Terdekat");
        jButtonhdekat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jTextFieldcheckin2.setText("Tanggal Check In");

        jTextFieldcheckout2.setText("Tanggal Check Out");

        jComboBoxkamar2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBoxharga2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Opsional", "Rp.0 - Rp.200.000", "Rp.200.000 - Rp.500.000", "Rp.500.000 - Rp.1.000.000", " " }));

        jButtoncarihoteldekat.setText("CARI HOTEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonback2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeljuduldekat)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnginap)
                            .addComponent(jLabelCheckin2)
                            .addComponent(jLabelCheckout2)
                            .addComponent(jLabelkamar2)
                            .addComponent(jLabelharga2))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxharga2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxkamar2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldcheckout2)
                            .addComponent(jTextFieldcheckin2)
                            .addComponent(jButtonhdekat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButtoncarihoteldekat)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonback2)
                    .addComponent(jLabeljuduldekat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnginap)
                    .addComponent(jButtonhdekat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckin2)
                    .addComponent(jTextFieldcheckin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckout2)
                    .addComponent(jTextFieldcheckout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelkamar2)
                    .addComponent(jComboBoxkamar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelharga2)
                    .addComponent(jComboBoxharga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtoncarihoteldekat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotelterdekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotelterdekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotelterdekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotelterdekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotelterdekat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonback2;
    private javax.swing.JButton jButtoncarihoteldekat;
    private javax.swing.JButton jButtonhdekat;
    private javax.swing.JComboBox jComboBoxharga2;
    private javax.swing.JComboBox jComboBoxkamar2;
    private javax.swing.JLabel jLabelCheckin2;
    private javax.swing.JLabel jLabelCheckout2;
    private javax.swing.JLabel jLabelharga2;
    private javax.swing.JLabel jLabeljuduldekat;
    private javax.swing.JLabel jLabelkamar2;
    private javax.swing.JLabel jLabelnginap;
    private javax.swing.JTextField jTextFieldcheckin2;
    private javax.swing.JTextField jTextFieldcheckout2;
    // End of variables declaration//GEN-END:variables
}
